"""added product catalog

Revision ID: 06306e68e954
Revises: 7ce923cb5e62
Create Date: 2024-07-23 16:40:44.665896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06306e68e954'
down_revision = '7ce923cb5e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_catalog', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product_catalog', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_catalog', type_='foreignkey')
    op.drop_column('product_catalog', 'user_id')
    # ### end Alembic commands ###
