"""updated invoice table

Revision ID: 49b37baf62fc
Revises: 89cdcb4daa6b
Create Date: 2024-07-09 14:52:00.428407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b37baf62fc'
down_revision = '89cdcb4daa6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('paid', sa.String(length=10), nullable=True))
    op.add_column('invoices', sa.Column('url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'url')
    op.drop_column('invoices', 'paid')
    # ### end Alembic commands ###
