"""updated subscription status

Revision ID: 89cdcb4daa6b
Revises: ebbf7152be7a
Create Date: 2024-07-09 13:37:20.392933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89cdcb4daa6b'
down_revision = 'ebbf7152be7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('status', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'status')
    # ### end Alembic commands ###
