"""has_seen_pricing toggle

Revision ID: 8c7f1fa58e98
Revises: 49b37baf62fc
Create Date: 2024-07-09 22:10:48.991385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7f1fa58e98'
down_revision = '49b37baf62fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_seen_pricing', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_seen_pricing')
    # ### end Alembic commands ###
