"""users insights and s3

Revision ID: bda2d62b7958
Revises: 8c7f1fa58e98
Create Date: 2024-07-16 12:50:47.535240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda2d62b7958'
down_revision = '8c7f1fa58e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('insights_keys', sa.String(length=400), nullable=True))
    op.add_column('users', sa.Column('data_marketplace_bucket', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data_marketplace_bucket')
    op.drop_column('users', 'insights_keys')
    # ### end Alembic commands ###
