"""added product catalog

Revision ID: c9996ec82b38
Revises: d104ee5f4aa1
Create Date: 2024-07-23 20:26:48.879183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9996ec82b38'
down_revision = 'd104ee5f4aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product_catalog', ['tier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_catalog', type_='unique')
    # ### end Alembic commands ###
