"""added product catalog

Revision ID: d104ee5f4aa1
Revises: 06306e68e954
Create Date: 2024-07-23 17:07:20.545620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd104ee5f4aa1'
down_revision = '06306e68e954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_catalog_user_id_fkey', 'product_catalog', type_='foreignkey')
    op.drop_column('product_catalog', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_catalog', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('product_catalog_user_id_fkey', 'product_catalog', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
