"""user last_gpt_question

Revision ID: ddc685f05c73
Revises: c9996ec82b38
Create Date: 2024-07-25 21:03:21.260111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddc685f05c73'
down_revision = 'c9996ec82b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_gpt_question', sa.Integer(), nullable=True))
    op.drop_column('users', 'last_question_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_question_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_gpt_question')
    # ### end Alembic commands ###
